name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the stack
        run: docker build -f Dockerfile.prod -t shigoto_q_production_react .
      - name: Tag Docker images 
        run: | 
          docker tag shigoto_q_production_react ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_react

      - name: Push Docker images 
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/shigoto_q_production_react
          export DOCKER_CONFIG=$(cat ~/.docker/config.json | base64 -w 0)

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: Shigoto-Q/sgt-infrastructure 
          event-type: build-successful
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'